blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    # Отображение блога
    path('', views.blog, name="blog")
]

bot/urls.py
from django.urls import path
from .views import TelegramWebhookView

urlpatterns = [
    path('api/BotWebhook', TelegramWebhookView.as_view(), name='telegram_webhook'),
]

params/urls.py
from django.contrib import admin
from django.urls import path, include
from params import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from params.sitemap import StaticViewSitemap
from params.views import obtain_token, verify_token, refresh_token

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('privacy_policy/', views.privacy_policy, name='privacy'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),

    path('api/', include('site_api.urls', namespace='api')),

    path('', include('site_forms.urls', namespace='site_forms')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('services/', include('services.urls', namespace='services')),
    path('products/', include('products.urls', namespace='products')),


    path('get-image-url/<str:image_name>/', views.get_image_url, name='get_image_url'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', views.robots_txt, name='robots_txt'),

    path('api/token/', obtain_token, name='token_obtain'),
    path('api/token/verify/', verify_token, name='token_verify'),
    path('api/token/refresh/', refresh_token, name='token_refresh'),

]



# Static and media files configuration
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from services.views import ServiceFormView, ServicesViews
from services.utils.autocompletes import ServiceAutocomplete, CategoryAutocomplete,\
    SubCategoryAutocomplete, TagsAutocomplete


app_name = "services"

urlpatterns = [
    # Автокомплиты
    path('service-autocomplete/', ServiceAutocomplete.as_view(), name='service-autocomplete'),
    path('category-autocomplete/', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    path('subcategory-autocomplete/', SubCategoryAutocomplete.as_view(), name='subcategory-autocomplete'),
    path('tag-autocomplete/', TagsAutocomplete.as_view(), name='tag-autocomplete'),
    # Отображение услуг
    path('services/', ServicesViews.as_view(), {'action': 'home_view'}, name="services"),
    path('services/<int:pk>/', ServicesViews.as_view(), {'action': 'get_service'}, name='service-detail'),
    path('autocomplete/', ServicesViews.as_view(), {'action': 'autocomplete'}, name='services-autocomplete'),
    path('services/<int:pk>/details/', ServicesViews.as_view(), {'action': 'get_service_details'}, name='service-details'),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'styles/base/header.css' %}">
        <link rel="stylesheet" href="{% static 'styles/base/background.css' %}">
        <link rel="stylesheet" href="{% static 'styles/base/loader.css' %}">
        <link rel="stylesheet" href="{% static 'styles/base/footer.css' %}">
        <script type="text/javascript" src="{% static 'js/loader.js' %}"></script>
        {% block extra_css %}{% endblock %}
        {% block extra_js %}{% endblock %}
    </head>
    <body class="loading">
        {% include 'loader.html' %}
        <div class="content-wrapper">
            <div id="custom-cursor">🔧</div>
            {% include 'header.html' %}
            <main>
            {% block content %}
            {% endblock %}

        </div>
    </main>
    {% include 'footer.html' %}
    </body>
</html>

templates/conact_popup.html
{% extends 'base.html' %}

{% block title %}Наши услуги{% endblock %}

{% block content %}
<!-- forms/templates/forms/popup.html -->
<div id="myModal" class="modal">
    <div class="modal-content">
        <span class="close">&times;</span>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}
<!-- Нихуёво было бы стили написать -->
<!-- CSP Нахуй блокнет эту залупу
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("openModalBtn");
    var span = document.getElementsByClassName("close")[0];

    btn.onclick = function() {
        modal.style.display = "block";
    }

    span.onclick = function() {
        modal.style.display = "none";
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
--->

templates/error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ошибка {{ status_code }}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/error/error.css' %}">
{% endblock %}
{% block content %}
    <div class="center background" data-display="flex" style="flex-direction:column;">
        <div class="main_wrapper">
            <div class="main">
                <div class="antenna">
                    <div class="antenna_shadow"></div>
                    <div class="a1"></div>
                    <div class="a1d"></div>
                    <div class="a2"></div>
                    <div class="a2d"></div>
                    <div class="a_base"></div>
                </div>
                <div class="tv">
                    <div class="cruve">
                        <svg
                            xml:space="preserve"
                            viewBox="0 0 189.929 189.929"
                            xmlns:xlink="http://www.w3.org/1999/xlink"
                            xmlns="http://www.w3.org/2000/svg"
                            version="1.1"
                            class="curve_svg"
                        >
                            <path
                            d="M70.343,70.343c-30.554,30.553-44.806,72.7-39.102,115.635l-29.738,3.951C-5.442,137.659,11.917,86.34,49.129,49.13
                        C86.34,11.918,137.664-5.445,189.928,1.502l-3.95,29.738C143.041,25.54,100.895,39.789,70.343,70.343z"
                            ></path>
                        </svg>
                    </div>
                    <div class="display_div">
                        <div class="screen_out">
                            <div class="screen_out1">
                                <div class="screen">
                                    <span class="notfound_text">{{ error_message }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="lines">
                        <div class="line1"></div>
                        <div class="line2"></div>
                        <div class="line3"></div>
                    </div>
                    <div class="buttons_div">
                        <div class="b1">
                        <div></div>
                        </div>
                        <div class="b2"></div>
                        <div class="speakers">
                            <div class="g1">
                                <div class="g11"></div>
                                <div class="g12"></div>
                                <div class="g13"></div>
                            </div>
                            <div class="g"></div>
                            <div class="g"></div>
                        </div>
                    </div>
                </div>
                <div class="bottom">
                    <div class="base1"></div>
                    <div class="base2"></div>
                    <div class="base3"></div>
                </div>
            </div>
            <div class="text_404">
                <div class="text_4041">{{ digit_1 }}</div>
                <div class="text_4042">{{ digit_2 }}</div>
                <div class="text_4043">{{ digit_3 }}</div>
            </div>
        </div>
        <div class="error-description-wrapper" data-display="flex">
            <h1 class="error-description-message">
                {{ error_message_full }}
            </h1>
        </div>
    </div>
{% endblock %}

templates/footer.html
<div class="footer">
    <div class="footer-content">
        <p>© 2024 Your Company. Все права защищены.</p>
        <div class="footer-links">
            <a href="{% url 'privacy' %}">Политика конфиденциальности</a>
            <a href="{% url 'terms_of_service' %}">Условия использования</a>
            <a tel="+375295410647">+375(29) 541-06-47</a>
        </div>
    </div>
</div>

templates/header.html
{% load static %}
<div class="content header" data-display="flex">
    <div class="logo">
        <img url="{% url 'home' %}" class="logo-img" src="{% static 'images/main_logo.webp' %}" alt="Агросервис">
        <img url="{% url 'home' %}" class="logo-text" src="{% static 'images/logo_text_white.webp' %}" alt="Foltz">
    </div>
    <div class="nav-buttons">
        <button class="header-button">
            <svg viewBox="0 0 16 16" class="bi bi-lightning-charge-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"></path>
            </svg>
            <a class="span" href="{% url 'services:services' %}">УСЛУГИ</a>
        </button>
        <button class="header-button">
            <svg viewBox="0 0 16 16" class="bi bi-lightning-charge-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"></path>
            </svg>
            <a class="span" href="{% url 'about' %}">О НАС</a>
        </button>
        <button class="header-button">
            <svg viewBox="0 0 16 16" class="bi bi-lightning-charge-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"></path>
            </svg>
            <a class="span" href="{% url 'blog:blog' %}">БЛОГ</a>
        </button>
        <button class="header-button">
            <svg viewBox="0 0 16 16" class="bi bi-lightning-charge-fill" fill="currentColor" height="16" width="16" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"></path>
            </svg>
            <a class="span" href="{% url 'services:services' %}">КОНТАКТЫ</a>
        </button>
    </div>
    <div class="burger-menu">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </div>
    <div class="content header" data-display="flex">
        <div class="logo">Логотип</div>
        <div class="nav-buttons">
            <a href="{% url 'home' %}">Главная</a>
            <a href="{% url 'services:services' %}">Услуги</a>
            <a href="{% url 'about' %}">О нас</a>
            <a href="{% url 'blog:blog' %}">Блог</a>
        </div>
        <div class="burger-menu">
            <div class="line"></div>
            <div class="line"></div>
            <div class="line"></div>
        </div>
    </div>
</div>

templates/loader.html
<div id="loading" class="preloader">
    <div class="loader"></div>
</div>

templates/privacy_policy.html
{% extends 'base.html' %}

{% block title %}Политика конфиденциальности{% endblock %}

{% block content %}
<div class="content background" data-display="flex">
    <h1>Страница с политикой конфиденциальности</h1> 
</div>
{% endblock %}

templates/terms_of_service.html
{% extends 'base.html' %}

{% block title %}Правила пользования{% endblock %}

{% block content %}
<!-- Кино не будет -->
<div class="content background" data-display="flex">
    <h1>Страница с правилами пользования</h1> 
</div>
{% endblock %}