bot/urls.py
from django.urls import path
from .views import TelegramWebhookView

urlpatterns = [
    path('api/BotWebhook', TelegramWebhookView.as_view(), name='telegram_webhook'),
]

params/urls.py
from django.contrib import admin
from django.urls import path, include
from params import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from params.sitemap import StaticViewSitemap
from params.views import obtain_token, verify_token, refresh_token

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('privacy_policy/', views.privacy_policy, name='privacy'),
    path('terms_of_service/', views.terms_of_service, name='terms_of_service'),

    path('api/', include('site_api.urls', namespace='api')),

    path('', include('site_forms.urls', namespace='site_forms')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('services/', include('services.urls', namespace='services')),
    path('products/', include('products.urls', namespace='products')),


    path('get-image-url/<str:image_name>/', views.get_image_url, name='get_image_url'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', views.robots_txt, name='robots_txt'),

    path('api/token/', obtain_token, name='token_obtain'),
    path('api/token/verify/', verify_token, name='token_verify'),
    path('api/token/refresh/', refresh_token, name='token_refresh'),

]



# Static and media files configuration
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from services.views import ServiceFormView, ServicesViews
from services.utils.autocompletes import ServiceAutocomplete, CategoryAutocomplete,\
    SubCategoryAutocomplete, TagsAutocomplete


app_name = "services"

urlpatterns = [
    # Автокомплиты
    path('service-autocomplete/', ServiceAutocomplete.as_view(), name='service-autocomplete'),
    path('category-autocomplete/', CategoryAutocomplete.as_view(), name='category-autocomplete'),
    path('subcategory-autocomplete/', SubCategoryAutocomplete.as_view(), name='subcategory-autocomplete'),
    path('tag-autocomplete/', TagsAutocomplete.as_view(), name='tag-autocomplete'),
    # Отображение услуг
    path('services/', ServicesViews.as_view(), {'action': 'home_view'}, name="services"),
    path('services/<int:pk>/', ServicesViews.as_view(), {'action': 'get_service'}, name='service-detail'),
    path('autocomplete/', ServicesViews.as_view(), {'action': 'autocomplete'}, name='services-autocomplete'),
    path('services/<int:pk>/details/', ServicesViews.as_view(), {'action': 'get_service_details'}, name='service-details'),
]

services/models.py
from django.db import models
from django.core.exceptions import ValidationError
from slugify import slugify
from django.utils import timezone
from services.utils.json_validators import validate_characteristics, validate_service
import os, json



def get_upload_to(instance, filename): 
    if isinstance(instance, Service):
        return os.path.join('media', 'services', f'service_{instance.title}', filename)
    elif isinstance(instance, ServiceSection):
        return os.path.join('media', 'services', f'service_{instance.service.pk}', 'sections', f'section_{instance.pk}', filename) 
    return os.path.join('media', 'uploads', filename)


class ServiceCategory(models.Model):
    name = models.CharField('Имя категории', max_length=50)
    slug = models.SlugField('Url представление', blank=True, unique=True)
    modified = models.DateTimeField('Дополнено', auto_now=True)


    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name



class ServiceSubCategory(models.Model):
    name = models.CharField('Имя подкатегории', max_length=50)
    slug = models.SlugField('Url представление', blank=True, unique=True)
    category = models.ForeignKey(
        to=ServiceCategory,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='К какой категории относится?'
    )
    modified = models.DateTimeField('Дополнено', auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class ServiceTags(models.Model):
    name = models.CharField('Имя тега', max_length=50)
    slug = models.SlugField('Url представление', blank=True, unique=True)
    modified = models.DateTimeField('Дополнено', auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name



class Service(models.Model):
    title = models.CharField('Заголовок', max_length=100, unique=True)
    preview_text = models.TextField(
        verbose_name='Краткое описание(превью)',
        max_length=200,
        blank=True,
        null=False
    )
    preview_video_url = models.URLField(
        verbose_name='Видео youtube(превью)',
        blank=True,
        null=True
    )
    preview_image = models.ImageField(
        verbose_name='Преввью картинка',
        upload_to=get_upload_to,
        blank=True,
        null=True
    )
    category = models.ForeignKey(
        to=ServiceCategory,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Какая категория?'
    )
    subcategory = models.ForeignKey(
        to=ServiceSubCategory,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Какая подкатегория?'
    )
    price = models.IntegerField('Цена', null=True)
    slug = models.SlugField('Url представление', blank=True, unique=True)
    tags = models.ManyToManyField(ServiceTags, blank=True)
    modified = models.DateTimeField('Дополнено', auto_now=True)

    def get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Service.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}{num}"
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)

    def get_related_services_from_json(self, json_data):
        data:dict = json.loads(json_data)
        title = data.get('title')
        category_name = data.get('category')
        subcategory_name = data.get('subcategory')
        if target_service := Service.objects.filter(
            title__icontains=title
        ).first():
            category = ServiceCategory.objects.filter(name=category_name).first() if category_name else target_service.category
            subcategory = ServiceSubCategory.objects.filter(name=subcategory_name).first() if subcategory_name else target_service.subcategory
            return (
                Service.objects.filter(category=category, subcategory=subcategory)
                .exclude(pk=target_service.pk)
                .distinct()
            )
        return []

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'



class ServiceSection(models.Model):
    order = models.PositiveIntegerField('Порядок', blank=True, null=True)
    subtitle = models.CharField('Подзаголовок', max_length=200, blank=True, null=True)
    content = models.TextField('Блок текста', blank=True, null=True)
    youtube_url = models.URLField('Видео youtube', blank=True, null=True)
    image = models.ImageField('Иллюстрация', upload_to=get_upload_to, blank=True, null=True)
    add = models.JSONField(
        verbose_name = 'JSON поле для рекламы(инфа для запроса)',
        validators=[validate_service],
        blank=True,
        null=True
    )
    characteristics = models.JSONField(
        verbose_name='Таблица',
        validators=[validate_characteristics],
        blank=True,
        null=True
    )
    service = models.ForeignKey(
        to=Service,
        related_name='service_section',
        on_delete=models.CASCADE,
        verbose_name='Какая услуга?'
    )

    def __str__(self):
        return f"{self.service.title} - {self.order}"

    def clean(self):
        fields = [self.image, self.youtube_url, self.subtitle, self.content]
        filled_fields = [field for field in fields if field]
        if len(filled_fields) > 1:
            raise ValidationError('Можно выбрать только одно поле для заполнения.')
        if not filled_fields:
            raise ValidationError('Необходимо заполнить хотя бы одно поле.')

    def save(self, *args, **kwargs):
        self.clean()
        if not self.order:
            max_order = ServiceSection.objects.filter(service=self.service).aggregate(max_order=models.Max('order'))['max_order']
            self.order = max_order + 1 if max_order is not None else 1
        else:
            conflicting_sections = ServiceSection.objects.filter(service=self.service, order=self.order).exclude(pk=self.pk)
            if conflicting_sections.exists():
                conflicting_sections.update(order=models.F('order') + 1)
        super().save(*args, **kwargs)
        self.service.modified = timezone.now()
        self.service.save()

    def delete(self, *args, **kwargs): 
        super().delete(*args, **kwargs)
        # Обновление порядка у оставшихся секций 
        sections = ServiceSection.objects.filter(service=self.service).order_by('order')
        for index, section in enumerate(sections, start=1):
            section.order = index 
            section.save()

    class Meta:
        ordering = ['order']
        verbose_name = 'Секция услуги'
        verbose_name_plural = 'Секции услуги'

services/views.py
import hashlib
from django.http import JsonResponse, HttpResponseNotModified,\
    HttpRequest, HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.http import http_date
from django.views import View
from site_forms.custom_form import ContactForm
from services.models import Service, ServiceCategory, ServiceSubCategory, ServiceTags
from common.dto import FormData
from common.aplications import SendAplications


class ServiceFormView(View):
    def form_view(self, request:HttpRequest) -> HttpResponseRedirect|HttpResponse:
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                form_data = FormData(
                    name = form.cleaned_data['name'],
                    phone = form.cleaned_data['phone'],
                    question = form.cleaned_data['question']
                )
                sendler = SendAplications(form_data)
                sendler.email()
                sendler.tg()
                return redirect('success')
        else:
            form = ContactForm()
        return render(request, 'contact.html', {'form': form})


class ServicesViews(View):
    def get(self, request:HttpRequest, *args, **kwargs) -> HttpResponse|HttpResponseNotModified|JsonResponse: 
        action = kwargs.pop('action', None) 
        if action == 'get_service':
            return self.get_service(request, *args, **kwargs) 
        elif action == 'get_service_details':
            return self.get_service_details(request, *args, **kwargs)
        elif action == 'service_search': 
            return self.service_search(request, *args, **kwargs) 
        elif action == 'home_view':
            return self.home_view(request, *args, **kwargs)


    def get_service(self, request:HttpRequest, *args, **kwargs) -> JsonResponse:
        service = Service.objects.get(pk=kwargs['pk'])
        content = {
            'title': service.title,
            'preview_image': service.preview_image.url if service.preview_image else None,
            'price': service.price
        }
        etag_content = f"{service.title}-{service.preview_image}-{service.price}"
        etag = hashlib.md5(etag_content.encode('utf-8')).hexdigest()
        if_none_match = request.headers.get('If-None-Match')
        if if_none_match == etag:
            return HttpResponseNotModified()
        response = JsonResponse(content)
        response['ETag'] = etag
        last_modified = service.modified
        response['Last-Modified'] = http_date(last_modified.timestamp())
        return response


    def get_service_details(self, request:HttpRequest, *args, **kwargs) -> HttpResponseNotModified|HttpResponse:
        service = get_object_or_404(Service, pk=kwargs['pk'])
        sections = service.service_section.all()
        etag_content = f"{service.title}-{service.preview_image}-{service.price}-{service.modified}"
        etag = hashlib.md5(etag_content.encode('utf-8')).hexdigest()
        if_none_match = request.headers.get('If-None-Match')
        if if_none_match == etag:
            return HttpResponseNotModified()
        last_modified = service.modified
        context = {
            'service': service,
            'sections': sections,
            'tags': service.tags.all(),
            'category': service.category
        }
        response = render(request, 'services/detail.html', context)
        response['ETag'] = etag
        response['Last-Modified'] = http_date(last_modified.timestamp())
        return response


    #TO DO Add subcategory in filter
    def service_search(self, request:HttpRequest) -> HttpResponse:
        title_query = request.GET.get('title', '')
        category_query = request.GET.get('category', '')
        tag_query = request.GET.get('tag', '')
        services = Service.objects.all()
        search_performed = False
        if title_query:
            services = services.filter(title__icontains=title_query)
            search_performed = True
        if category_query:
            services = services.filter(category__name__icontains=category_query)
            search_performed = True
        if tag_query:
            services = services.filter(tags__name__icontains=tag_query)
            search_performed = True
        context = {'services': services, 'search_performed': search_performed}
        return render(request, 'services/base.html', context)


    #TO DO Add subcategory in filter
    def home_view(self, request: HttpRequest) -> HttpResponseNotModified | HttpResponse:
        title_query = request.GET.get('title', '')
        category_query = request.GET.get('category', '')
        tag_query = request.GET.get('tag', '')
        subcategory_query = request.GET.get('subcategory', '')
        services_by_category = {}
        search_performed = False
        categories = ServiceCategory.objects.all()
        page_number = request.GET.get('page')
        if title_query or category_query or tag_query:
            search_performed = True
            services = Service.objects.all()
            if title_query:
                services = services.filter(title__icontains=title_query)
            if category_query:
                services = services.filter(category__name__icontains=category_query)
            if subcategory_query:
                services = services.filter(subcategory__name_icontains=subcategory_query)
            if tag_query:
                services = services.filter(tags__name__icontains=tag_query)
        else:
            for category in categories:
                services = Service.objects.filter(category=category)[:4]
                services_by_category[category] = services
            paginator = Paginator(categories, 1)
            page_obj = paginator.get_page(page_number)
        etag_content = f"{title_query}-{category_query}-{subcategory_query}-{tag_query}-{page_number}"
        etag = hashlib.md5(etag_content.encode('utf-8')).hexdigest()
        if_none_match = request.headers.get('If-None-Match')
        if if_none_match == etag:
            return HttpResponseNotModified()
        if not search_performed and categories.exists():
            last_modified = categories.latest('modified').modified
        elif search_performed and services.exists():
            last_modified = services.latest('modified').modified
        else:
            last_modified = None
        context = {
            'services_by_category': services_by_category,
            'page_obj': None if search_performed else page_obj,
            'services': services if search_performed else None,
            'search_performed': search_performed
        }
        response = render(request, 'services/base.html', context)
        response['ETag'] = etag
        if last_modified:
            response['Last-Modified'] = http_date(last_modified.timestamp())
        return response

services/templates/services/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Home</title>
    <link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base/header.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base/background.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base/loader.css' %}">
    <link rel="stylesheet" href="{% static 'styles/base/footer.css' %}">
    <link rel="stylesheet" href="{% static 'styles/services/search_form.css' %}">
    <script type="text/javascript" src="{% static 'js/loader.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class = "loading">
    {% include 'loader.html' %}
    {% include 'header.html' %}
    <h1>Service Home</h1>
    {% include 'services/search_form.html' %}
    {% if not search_performed %}
        {% include 'services/home.html' %}
    {% else %}
        {% include 'services/search_results.html' %}
    {% endif %}
    {% include 'footer.html' %}
</body>
</html>

services/templates/services/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ service.title }}</title>
</head>
<body>
    <h1>{{ service.title }}</h1>
    <img src="{{ service.preview_image.url }}" alt="{{ service.title }}">
    <p>Цена: {{ service.price }}</p>
    <p>Категория: {{ category.name }}</p>
    <p>Метки: 
        {% for tag in tags %}
            <span>{{ tag.name }}</span>{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>

    <h2>Секции</h2>
    <ul>
        {% for section in sections %}
            <li>
                {% if section.image %}
                    <img src="{{ section.image.url }}" alt="Section Image">
                {% endif %}
                {% if section.youtube_url %}
                    <p>ютуб <a href="{{ section.youtube_url }}">{{ section.youtube_url }}</a></p>
                {% endif %}
                {% if section.subtitle %}
                    <h3>{{ section.subtitle }}</h3>
                {% endif %}
                {% if section.content %}
                    <p>{{ section.content }}</p>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

services/templates/services/home.html
<div id="category-services">
    {% for category, services in services_by_category.items %}
        <h2>{{ category.name }}</h2>
        <ul>
            {% for service in services %}
                <li>
                    <h3>{{ service.title }}</h3>
                    <p>Price: {{ service.price }}</p>
                    <img src="{{ service.preview_image.url }}" alt="{{ service.title }}">
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
</div>

<!-- Пагинация -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

services/templates/services/search_form.html
{% load static %}
<form id="search-form" method="get">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
        <label for="title">Title:</label>
        <input type="text" id="title" name="title" class="django-select2" data-autocomplete-light-url="{% url 'services:service-autocomplete' %}" autocomplete="on">
        <div id="title-suggestions" class="suggestions-box"></div>

        <label for="category">Category:</label>
        <input type="text" id="category" name="category" class="django-select2" data-autocomplete-light-url="{% url 'services:category-autocomplete' %}" autocomplete="on">
        <div id="category-suggestions" class="suggestions-box"></div>

        <label for="subcategory">Subcategory</label>
        <input type="text" id="subcategory" name="category" class="django-select2" data-autocomplete-light-url="{% url 'services:subcategory-autocomplete'%}" autocomplete="on">
        <div id="subcategory-suggestions" class="suggestions-box"></div>

        <label for="tag">Tag:</label>
        <input type="text" id="tag" name="tag" class="django-select2" data-autocomplete-light-url="{% url 'services:tag-autocomplete' %}" autocomplete="on">
        <div id="tag-suggestions" class="suggestions-box"></div>

        <button type="submit">Search</button>
    </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.js"></script>
    <script src="{% static 'js/services/your_dal_init.js' %}"></script>

services/templates/services/search_results.html
<div id="search-results">
    {% if services %}
        <h2>Search Results:</h2>
        <ul>
            {% for service in services %}
                <li>
                    <h3>{{ service.title }}</h3>
                    <p>Price: {{ service.price }}</p>
                    <img src="{{ service.preview_image.url }}" alt="{{ service.title }}">
                </li>
            {% endfor %}
        </ul>
    {% elif search_performed %}
        <p>No services found.</p>
    {% endif %}
</div>